# Generated by Django 4.0.4 on 2022-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=12),
            preserve_default=False,
        ),
    ]
