# Generated by Django 4.0.4 on 2022-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_offer_id_alter_product_id_alter_rate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
