# Generated by Django 4.0.4 on 2022-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
