# Generated by Django 4.0.4 on 2022-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_offer_description_en_offer_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avatar',
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/products/'),
        ),
    ]
