# Generated by Django 4.0.4 on 2022-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_offer_name_en_offer_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
