# Generated by Django 4.0.4 on 2022-06-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_paymenttypes_subscription_payment_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTypes',
            new_name='PaymentType',
        ),
    ]
