# Generated by Django 4.0.4 on 2022-06-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_paymenttypes_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multi_plane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rate',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
