# Generated by Django 4.0.4 on 2022-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_multi_plane_rate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
