# Generated by Django 4.0.4 on 2022-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
