# Generated by Django 4.0.4 on 2022-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_offer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
