# Generated by Django 4.0.4 on 2022-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_offer_phone_number_subscription_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desctiption',
            field=models.TextField(null=True),
        ),
    ]
