# Generated by Django 4.0.4 on 2022-06-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desctiption',
            new_name='description',
        ),
    ]
