# Generated by Django 4.0.4 on 2022-06-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_socialauthuser_alter_subscription_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialAuthUser',
        ),
    ]
