# Generated by Django 4.0.4 on 2022-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_questions_delete_socialauthuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
