# Generated by Django 4.0.4 on 2022-06-14 10:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_subscription_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
