# Generated by Django 4.0.4 on 2022-06-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_subscription_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='FAQ',
        ),
    ]
