# Generated by Django 4.0.4 on 2022-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_questions_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttask',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
